#include <Arduino.h>
#include <Wire.h>


#define MAIN2 PA2 //MOTOR DA ESQUERDA SENTIDO ANTI-HORÁRIO
#define MAIN1 PB13 //MOTOR DA ESQUERDA SENTIDO HORÁRIO

#define MBIN2 PB0 //MOTOR DA DIREITA SENTIDO ANTI-HORÁRIO
#define MBIN1 PA7 //MOTOR DA DIREITA SENTIDO HORÁRIO

#define PWMA PB8 //PORTA PONTE H
#define PWMB PA1 //PORTA PONTE H

#define LED1 PC13 //LED INDICAÇÃO ENVIANDO CORRENTE SENSORES

#define BTN1 PB3 //BOTÃO CALIBRAÇÃO
#define BTN2 PB4 //BOTÃO LIGAR
